@url_dev=http://localhost:2024/v1/api

### signup
POST {{url_dev}}/user/signup
Content-Type: application/json

{
  "name": "test6",
  "email": "test1.email@example.com",
  "password": "your_password"
}