@url_dev=http://localhost:2024/v1/api

### signup
POST {{url_dev}}/user/signup
Content-Type: application/json
x-api-key:c17242b8a35e777b7524ecc4bf724ad003462961e039f1f4ec0d7081bb71cf3c2dbae83dac25479bdfc9851aa93ff210951e75c6fa8a45e653a6ed2991a740fd

{
  "name": "shop1",
  "email": "shop1.email@example.com",
  "password": "shop1",
  "role": "shop"
}